# Generated by Django 5.2.6 on 2026-05-03 06:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FineStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('total_fines_issued', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fines_paid', models.IntegerField(default=0)),
                ('revenue_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_notifications_sent', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fine Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(db_index=True, help_text='Vehicle registration number plate (e.g., BA 1234 AB)', max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Motorcycle', 'Motorcycle'), ('Car', 'Car'), ('Bus', 'Bus'), ('Truck', 'Truck'), ('Auto-rickshaw', 'Auto-rickshaw'), ('Scooter', 'Scooter'), ('Taxi', 'Taxi'), ('Other', 'Other')], max_length=50)),
                ('vehicle_model', models.CharField(blank=True, help_text='Vehicle make and model (e.g., Toyota Fortuner)', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle engine/chassis number', max_length=50)),
                ('owner_name', models.CharField(help_text="Registered owner's name", max_length=150)),
                ('owner_phone', models.CharField(help_text="Owner's phone number for notifications", max_length=15)),
                ('owner_address', models.TextField(blank=True, help_text="Owner's registered address")),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_fine_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_explanation', models.TextField(help_text='Detailed description of the traffic violation')),
                ('violation_date', models.DateTimeField(help_text='Date and time of violation')),
                ('location', models.CharField(blank=True, help_text='Location where violation occurred', max_length=255)),
                ('fine_amount', models.DecimalField(decimal_places=2, help_text='Fine amount in rupees', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('photo_proof', models.ImageField(help_text='Photo evidence of the violation', upload_to='fine_proofs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Notified', 'Notified'), ('Acknowledged', 'Acknowledged'), ('Paid', 'Paid'), ('Disputed', 'Disputed'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When notification was sent to vehicle owner', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When violator acknowledged the fine', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When fine was paid', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(help_text='Police officer who issued the fine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_fines', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fineapp.vehicle')),
                ('violation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='fineapp.violationtype')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('App', 'App Notification (Nagarik)'), ('WhatsApp', 'WhatsApp')], default='App', max_length=20)),
                ('recipient', models.CharField(help_text='Phone number, email, or user ID', max_length=150)),
                ('message', models.TextField(help_text='Notification message content')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('response', models.TextField(blank=True, help_text='Response from notification service')),
                ('fine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fineapp.fine')),
            ],
            options={
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(help_text="Officer's badge/ID number", max_length=50, unique=True)),
                ('department', models.CharField(blank=True, help_text='Police department/station', max_length=150)),
                ('designation', models.CharField(blank=True, help_text='Job title (e.g., Traffic Police, Constable)', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_officer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Police Officers',
            },
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['vehicle', '-issued_at'], name='fineapp_fin_vehicle_28d8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['status', '-issued_at'], name='fineapp_fin_status_11b942_idx'),
        ),
        migrations.AddIndex(
            model_name='fine',
            index=models.Index(fields=['issued_by', '-issued_at'], name='fineapp_fin_issued__3e131c_idx'),
        ),
    ]
